# Version information for bidoc package
# This file is automatically generated by setuptools_scm
# Do not edit this file manually

try:
    from setuptools_scm import get_version

    __version__ = get_version(root="..", relative_to=__file__)
except (ImportError, LookupError):
    # Fallback for installed packages or when setuptools_scm is not available
    try:
        from importlib.metadata import PackageNotFoundError, version
    except ImportError:
        # Python < 3.8
        from importlib_metadata import PackageNotFoundError, version

    try:
        __version__ = version("bidoc")
    except PackageNotFoundError:
        # Package is not installed
        __version__ = "unknown"
